// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0UtqrWXg4t6H3rxdGxrq5TVQx7LSP7Mw',
    appId: '1:457081428821:web:4ec9533f12d91300c5addc',
    messagingSenderId: '457081428821',
    projectId: 'dsx-app',
    authDomain: 'dsx-app.firebaseapp.com',
    storageBucket: 'dsx-app.firebasestorage.app',
    measurementId: 'G-JFBFV0N3MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArcvyHZutiUNbYIgT-AgSET839k6aLvGo',
    appId: '1:457081428821:android:6fcbe9b9c29a9014c5addc',
    messagingSenderId: '457081428821',
    projectId: 'dsx-app',
    storageBucket: 'dsx-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdEeKdLCveC6cmsWsoV8hEwxsmGtPJ35s',
    appId: '1:457081428821:ios:9690ea6adc9935e2c5addc',
    messagingSenderId: '457081428821',
    projectId: 'dsx-app',
    storageBucket: 'dsx-app.firebasestorage.app',
    iosBundleId: 'com.deversol.dsxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdEeKdLCveC6cmsWsoV8hEwxsmGtPJ35s',
    appId: '1:457081428821:ios:9690ea6adc9935e2c5addc',
    messagingSenderId: '457081428821',
    projectId: 'dsx-app',
    storageBucket: 'dsx-app.firebasestorage.app',
    iosBundleId: 'com.deversol.dsxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0UtqrWXg4t6H3rxdGxrq5TVQx7LSP7Mw',
    appId: '1:457081428821:web:8ae2d58e1e2f0c10c5addc',
    messagingSenderId: '457081428821',
    projectId: 'dsx-app',
    authDomain: 'dsx-app.firebaseapp.com',
    storageBucket: 'dsx-app.firebasestorage.app',
    measurementId: 'G-36VDX0Q9H8',
  );
}
